name: GitHub  Test
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Telegram
      #   uses: azkadev/telegram@main
      - name: List Dir
        shell: bash
        run: ls