name: GitHub Test
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     repository: azkadev/azkadev
      #     ref: main
      - name: Add Telegram Action Azkadev
        uses: azkadev/telegram@main
      - name: List Dir
        shell: bash
        run: |
          pwd
          ls
          flutter_distributor