name: GitHub  Test
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add Telegram Action Azkadev
        uses: azkadev/telegram@main
      - name: List Dir
        shell: bash
        run: pwd